name: CI Pipeline

on:
  push:
    branches: ['*']

jobs:
  server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r server/requirements.txt

      - name: Run server tests
        run: |
          cd server
          python -m unittest tests/test*.py

  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Kotlin client tests
        run: |
          cd client
          ./gradlew test

  lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Run flake8
        run: |
          cd server
          python -m flake8 rpc_demo_server tests

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r server/requirements.txt

      - name: Run server-client combination
        run: |
          (cd client && ./gradlew run)

      - name: Run server with simple client
        run: |
          (cd client && ./gradlew run -PserverPath=../server/rpc_demo_server/simple.py)

      - name: Run server with debug logging
        run: |
          (cd client && ./gradlew run -PlogLevel=DEBUG)
